version: 2
updates:
  - directories: 
      - "**/*"
    package-ecosystem: terraform
    rebase-strategy: auto
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"
